name: Cleanup Pending Orders

on:
  schedule:
    - cron: "*/5 * * * *"  # Executa a cada 5 minutos (UTC)

jobs:
  call-cleanup-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call cleanupPendingOrders API
        run: curl -s -X GET https://floricultura-server.vercel.app/api/orders/cleanup-pending
